# A simple airshipctl config file for using treasuremap
apiVersion: airshipit.org/v1alpha1
kind: Config
currentContext: target-cluster
managementConfiguration:
  treasuremap:
    insecure: true
    systemActionRetries: 30
    systemRebootDelay: 30
    type: redfish
contexts:
  target-cluster:
    contextKubeconf: target-cluster_target
    managementConfiguration: treasuremap
    manifest: treasuremap
manifests:
  treasuremap:
    # Use local repos in the home directory instead of the "pulled" ones in /tmp
    targetPath: /home/user
    phaseRepositoryName: treasuremap
    repositories:
      airshipctl:
        checkout:
          commitHash: 9caf5ed4f68e7f78ba60db04580701e3c9ba2c41
        url: /home/user/airshipctl
      treasuremap:
        url: /home/user/treasuremap

    # Select between different treasuremap site metadatas:
    metadataPath: /manifests/site/test-site/metadata.yaml
    # metadataPath: /manifests/site/reference-airship-core/metadata.yaml
    # metadataPath: /manifests/site/reference-multi-tenant/metadata.yaml
